name = "Plugins"
uuid = "231a7ae5-8495-40ed-9891-ff920a14b9bd"
authors = ["Krisztián Schaffer"]
version = "0.1.1"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
