name = "Plugins"
uuid = "231a7ae5-8495-40ed-9891-ff920a14b9bd"
authors = ["Krisztián Schaffer"]
version = "0.4.2"

[deps]

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
